### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by hjarrell** [CarlosFdez/SpueBox#2]
Hi I was wondering if it was possible if you could add a license to this repo (like MIT, https://choosealicense.com/licenses/mit/). I've been searching for a way to play youtube links with discord.py after the rewrite and yours was the best I could find.

**Comment by CarlosFdez** [comment]
Surprised, I'd expect there to be better examples nowadays, but perhaps they're closed source. That said I haven't been keeping up with discord.py releases. There are probably better ways to do half the things I'm doing.

MIT is my standard go-to so added it anyways. Have fun.

**Comment by hjarrell** [comment]
Thank you!
