### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by Vl4dim1r** [CarlosFdez/SpueBox#4]
I am getting this issue when I try to play anything from youtube. Am I doing something wrong? It was working for a couple weeks, then just started giving me this error. 

Nevermind, updating youtube-dl in the pipenv fixed this issue!

**Comment by CarlosFdez** [comment]
Yup, youtube changes often so youtube dl also has to follow suit. I'm glad they're still updating often because trying to keep up with youtube on your own sounds like a nightmare.
